<a href="https://colab.research.google.com/github/muhammed-sajid/Machine-Learning/blob/main/ML4Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [109]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()

df = pd.DataFrame(data= data.data, columns= data.feature_names)
print(df.head())

   mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0           

#Preprocessing Steps
#Handling Missing Values:#
 The breast cancer dataset from sklearn is clean and does not contain missing values. However, if there were missing values, we could use techniques like imputation (mean, median, or mode) or drop rows/columns with missing values.

#Feature Scaling:#
The features in this dataset have different scales. Scaling is necessary for algorithms like SVM, k-NN, and Logistic Regression, which are sensitive to the magnitude of the features. We use StandardScaler to standardize the features to have a mean of 0 and a standard deviation of 1.

In [110]:
df['target'] = data.target
print(df.head())

   mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0             

In [111]:
print("Handling Missing Values:")
print(df.isnull().sum())

Handling Missing Values:
mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
target                     0
dtype: int64


In [112]:
X = df.drop('target', axis=1)
y = df['target']

In [113]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
Scaler = StandardScaler()
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.3, random_state=42)
X_train = Scaler.fit_transform(X_train)
X_test = Scaler.transform(X_test)

# Logistic Regression


 Logistic Regression is a linear model used for binary classification. It estimates the probability of a sample belonging to a particular class using the logistic function.

In [114]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
log_reg  = LogisticRegression()
log_reg.fit(X_train, y_train)

LogisticRegression()

In [115]:
# Predict and evaluate
Linear_y_pred = log_reg.predict(X_test)

print("Logistic Regression Accuracy\n")
Log_acc = accuracy_score(y_test, Linear_y_pred)
print("Logistic Accuracy:",Log_acc)
Log_class_report = classification_report(y_test, Linear_y_pred)
print("\nLogistic classification report\n",Log_class_report)
log_conf_matrix  = confusion_matrix(y_test, Linear_y_pred)
print("\nLogistic confusion matrix\n",log_conf_matrix)

Logistic Regression Accuracy

Logistic Accuracy: 0.9824561403508771

Logistic classification report
               precision    recall  f1-score   support

           0       0.97      0.98      0.98        63
           1       0.99      0.98      0.99       108

    accuracy                           0.98       171
   macro avg       0.98      0.98      0.98       171
weighted avg       0.98      0.98      0.98       171


Logistic confusion matrix
 [[ 62   1]
 [  2 106]]


# Decision Tree Classifier

 A Decision Tree splits the data into subsets based on feature values, creating a tree-like structure. It makes decisions by following the path from the root to a leaf node.

In [116]:
from sklearn.tree import DecisionTreeClassifier

dt_classifier = DecisionTreeClassifier()
dt_classifier.fit(X_train, y_train)

DecisionTreeClassifier()

In [117]:
# Predict and evaluate
Decision_y_pred = dt_classifier.predict(X_test)

print("Decision Tree Classifier\n")
Decision_acc = accuracy_score(y_test, Decision_y_pred)
print("Decision Accuracy:",Log_acc)
Decision_class_report = classification_report(y_test, Decision_y_pred)
print("\nDecision classification report\n",Decision_class_report)
Decision_conf_matrix  = confusion_matrix(y_test, Decision_y_pred)
print("\nDecision confusion matrix\n",Decision_conf_matrix)

Decision Tree Classifier

Decision Accuracy: 0.9824561403508771

Decision classification report
               precision    recall  f1-score   support

           0       0.87      0.95      0.91        63
           1       0.97      0.92      0.94       108

    accuracy                           0.93       171
   macro avg       0.92      0.93      0.93       171
weighted avg       0.93      0.93      0.93       171


Decision confusion matrix
 [[60  3]
 [ 9 99]]


# Random Forest Classifier

 Random Forest is an ensemble method that builds multiple decision trees and combines their outputs to improve generalization and reduce overfitting.

In [118]:
from sklearn.ensemble import RandomForestClassifier

rf_classifier = RandomForestClassifier()
rf_classifier.fit(X_train, y_train)

RandomForestClassifier()

In [119]:
# Predict and evaluate
Random_y_pred = rf_classifier.predict(X_test)

print("Random Forest Classifier\n")
Random_acc = accuracy_score(y_test, Random_y_pred)
print("Random  Accuracy:",Log_acc)
Random_class_report = classification_report(y_test, Random_y_pred)
print("\nRandom classification report\n",Random_class_report)
Random_conf_matrix  = confusion_matrix(y_test, Random_y_pred)
print("\nRandom confusion matrix\n",Random_conf_matrix)

Random Forest Classifier

Random  Accuracy: 0.9824561403508771

Random classification report
               precision    recall  f1-score   support

           0       0.97      0.94      0.95        63
           1       0.96      0.98      0.97       108

    accuracy                           0.96       171
   macro avg       0.97      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171


Random confusion matrix
 [[ 59   4]
 [  2 106]]


# Support Vector Machine (SVM)

SVM finds the hyperplane that best separates the classes in the feature space. It can use kernel functions to handle non-linear relationships.


In [120]:
from sklearn.svm import SVC

svm = SVC()
svm.fit(X_train, y_train)

SVC()

In [121]:
#predict and evaluate
svm_y_pred = svm.predict(X_test)

print(" Support Vector Machine: \n")
svm_acc = accuracy_score(y_test, svm_y_pred)
print("SVM Accuracy:",svm_acc)
svm_class_report = classification_report(y_test, svm_y_pred)
print("\nSVM Classifiaction report:\n",svm_class_report)
svm_conf_matrix = confusion_matrix(y_test, svm_y_pred)
print("\nSVM confusion matrix:\n", svm_conf_matrix)

 Support Vector Machine: 

SVM Accuracy: 0.9766081871345029

SVM Classifiaction report:
               precision    recall  f1-score   support

           0       0.97      0.97      0.97        63
           1       0.98      0.98      0.98       108

    accuracy                           0.98       171
   macro avg       0.97      0.97      0.97       171
weighted avg       0.98      0.98      0.98       171


SVM confusion matrix:
 [[ 61   2]
 [  2 106]]


# k-Nearest Neighbors (k-NN)

k-NN classifies a sample based on the majority class among its k-nearest neighbors in the feature space.


In [122]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [123]:
#predict and evaluate
knn_y_pred = knn.predict(X_test)

print(" k-Nearest Neighbors: \n")
knn_acc = accuracy_score(y_test, knn_y_pred)
print("KNN Accuracy:",knn_acc)
knn_class_report = classification_report(y_test, knn_y_pred)
print("\nSVM Classifiaction report:\n",knn_class_report)
knn_conf_matrix = confusion_matrix(y_test, knn_y_pred)
print("\nSVM confusion matrix:\n", knn_conf_matrix)

 k-Nearest Neighbors: 

KNN Accuracy: 0.9590643274853801

SVM Classifiaction report:
               precision    recall  f1-score   support

           0       0.95      0.94      0.94        63
           1       0.96      0.97      0.97       108

    accuracy                           0.96       171
   macro avg       0.96      0.95      0.96       171
weighted avg       0.96      0.96      0.96       171


SVM confusion matrix:
 [[ 59   4]
 [  3 105]]


#3. Model Comparison


After training and evaluating the models, we compare their performance based on accuracy:

In [124]:
result = {
    'Model' : ['Logistic Regression', 'Decision Tree Classifier', 'Random Forest classifier', 'Support Vector Machine', 'K-Nearest Neighbour'],
    'Accuracy' : [Log_acc, Decision_acc, Random_acc, svm_acc, knn_acc]
}

In [125]:
result_data = pd.DataFrame(result)
print(result_data)

                      Model  Accuracy
0       Logistic Regression  0.982456
1  Decision Tree Classifier  0.929825
2  Random Forest classifier  0.964912
3    Support Vector Machine  0.976608
4       K-Nearest Neighbour  0.959064


In [126]:
print("Model Comparison:")
best_model = result_data.loc[result_data['Accuracy'].idxmax()]
worst_model = result_data.loc[result_data['Accuracy'].idxmin()]
print("The best performing model was:",best_model['Accuracy'])
print("The worst performing model was:", worst_model['Accuracy'])

Model Comparison:
The best performing model was: 0.9824561403508771
The worst performing model was: 0.9298245614035088


#Create a Comparison Table

In [128]:
def evaluate_classifier(model, model_name, X_train, X_test, y_train, y_test):
  model.fit(X_train, y_train)

  y_pred = model.predict(X_test)

  report = classification_report(y_test, y_pred, output_dict=True)

  metrics = {
      "Algorithm": model_name,
      "Precision (0)" : report["0"]['precision'],
      "Recall (0)" : report["0"]['recall'],
      "F1-Score (0)": report["0"]['f1-score'],
      "Precision (1)" : report["1"]['precision'],
      "Recall (1)" : report["1"]['recall'],
      "F1-Score (1)": report["1"]['f1-score'],
      "Accuracy" : accuracy_score(y_test, y_pred)

  }
  return metrics

classifiers = [
    ("Logistic Regression", LogisticRegression()),
    ("Decision Tree", DecisionTreeClassifier(random_state=42)),
    ("Random Forest", RandomForestClassifier(random_state=42)),
    ("SVM", SVC(kernel='linear', random_state=42)),
    ("k-NN", KNeighborsClassifier(n_neighbors=5))
]
results = []
for name, model in classifiers:
    metrics = evaluate_classifier(model, name, X_train, X_test, y_train, y_test)
    results.append(metrics)

comparison_table = pd.DataFrame(results)

print(comparison_table)


             Algorithm  Precision (0)  Recall (0)  F1-Score (0)  \
0  Logistic Regression       0.968750    0.984127      0.976378   
1        Decision Tree       0.895522    0.952381      0.923077   
2        Random Forest       0.983333    0.936508      0.959350   
3                  SVM       0.968254    0.968254      0.968254   
4                 k-NN       0.951613    0.936508      0.944000   

   Precision (1)  Recall (1)  F1-Score (1)  Accuracy  
0       0.990654    0.981481      0.986047  0.982456  
1       0.971154    0.935185      0.952830  0.941520  
2       0.963964    0.990741      0.977169  0.970760  
3       0.981481    0.981481      0.981481  0.976608  
4       0.963303    0.972222      0.967742  0.959064  
